import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#eef0ff',
        'outline-variant': '#bcc9c6',
        'surface-bright': '#faf8ff',
        'on-tertiary-fixed': '#001849',
        'on-secondary-container': '#007230',
        surface: '#faf8ff',
        primary: '#00685f',
        'surface-variant': '#dae2fd',
        'on-error-container': '#93000a',
        'primary-fixed': '#89f5e7',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#005049',
        'on-surface-variant': '#3d4947',
        'on-surface': '#131b2e',
        outline: '#6d7a77',
        'on-primary': '#ffffff',
        'surface-tint': '#006a61',
        'on-secondary-fixed': '#002109',
        'secondary-fixed-dim': '#62df7d',
        'primary-fixed-dim': '#6bd8cb',
        'surface-container-highest': '#dae2fd',
        background: '#faf8ff',
        'on-secondary-fixed-variant': '#005320',
        'on-tertiary-fixed-variant': '#003fa4',
        'inverse-surface': '#283044',
        'on-background': '#131b2e',
        'secondary-container': '#7cf994',
        'tertiary-fixed': '#dae1ff',
        'on-error': '#ffffff',
        'primary-container': '#008378',
        tertiary: '#2656bd',
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#b3c5ff',
        'surface-container': '#eaedff',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#f4fffc',
        'surface-container-high': '#e2e7ff',
        secondary: '#006e2d',
        'inverse-primary': '#6bd8cb',
        'on-tertiary-container': '#fefcff',
        'surface-dim': '#d2d9f4',
        'secondary-fixed': '#7ffc97',
        'tertiary-container': '#456fd7',
        'surface-container-low': '#f2f3ff',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['var(--font-display)', 'Public Sans', 'sans-serif'],
        body: ['var(--font-body)', 'Inter', 'sans-serif'],
        label: ['var(--font-body)', 'Inter', 'sans-serif'],
      },
      boxShadow: {
        ambient: '0 12px 32px -4px rgba(19, 27, 46, 0.06)',
      },
    },
  },
  plugins: [],
};

export default config;
